-- 便签板：位置、层级、颜色
ALTER TABLE memos ADD COLUMN IF NOT EXISTS pos_x DOUBLE PRECISION;
ALTER TABLE memos ADD COLUMN IF NOT EXISTS pos_y DOUBLE PRECISION;
ALTER TABLE memos ADD COLUMN IF NOT EXISTS z_index INTEGER NOT NULL DEFAULT 1;
ALTER TABLE memos ADD COLUMN IF NOT EXISTS color TEXT NOT NULL DEFAULT 'yellow';
