-- 便签四象限分类与尺寸
ALTER TABLE memos ADD COLUMN IF NOT EXISTS quadrant TEXT;
ALTER TABLE memos ADD COLUMN IF NOT EXISTS width DOUBLE PRECISION;
ALTER TABLE memos ADD COLUMN IF NOT EXISTS height DOUBLE PRECISION;
